apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-practice-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - java-practice.example.com
      secretName: java-practice-tls
  rules:
    - host: java-practice.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-java-practice-service
                port:
                  number: 80
