apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-gitops-demo-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/yuemj8665/spring-gitops-demo.git
    targetRevision: main
    path: k8s/overlays/dev  # Kustomize overlay 경로
    
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-gitops-demo-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
