apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spring-gitops-demo-dev

namePrefix: dev-

resources:
  - ../../base

# 이미지 태그 오버라이드 (로컬 Docker 이미지 사용)
images:
  - name: spring-gitops-demo
    newName: spring-gitops-demo_20260125
    newTag: "20260125_1712"

# ConfigMap 패치
configMapGenerator:
  - name: spring-gitops-demo-config
    behavior: merge
    literals:
      - APP_MESSAGE=Hello from DEV!
      - SPRING_PROFILES_ACTIVE=dev

# 레플리카 수 조정
replicas:
  - name: spring-gitops-demo
    count: 1
