apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: java-practice-dev

namePrefix: dev-

resources:
  - ../../base

# 이미지 태그 오버라이드
images:
  - name: java-practice
    newName: registry.gitlab.com/your-group/java-practice
    newTag: develop

# ConfigMap 패치
configMapGenerator:
  - name: java-practice-config
    behavior: merge
    literals:
      - APP_MESSAGE=Hello from DEV!
      - SPRING_PROFILES_ACTIVE=dev

# 레플리카 수 조정
replicas:
  - name: java-practice
    count: 1
